In [1]:
import numpy as np

## NumPy Basics

### Array Initialization

In [2]:
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_array)

[[1 2 3]
 [4 5 6]]


### Get Dimensions

In [4]:
print(array.ndim)
print(twod_array.ndim)

1
2


### Get Shape

In [5]:
print(array.shape)
print(twod_array.shape)

(3,)
(2, 3)


### Get Type

In [6]:
array.dtype

dtype('int32')

### Define the Type

In [7]:
array = np.array([1, 2, 3], dtype='int16')
array.dtype

dtype('int16')

### Size

In [8]:
print(f"**********************************************************************")
print(f"Array has type {array.dtype} which means that every item takes {array.itemsize} bytes.")
print(f"2D Array has {array.size} elements.")
print(f"Array total size is {array.nbytes} bytes.")
print(f"**********************************************************************")
print(f"2D Array has type {twod_array.dtype} which means that every item takes {twod_array.itemsize} bytes.")
print(f"2D Array has {twod_array.size} elements.")
print(f"2D Array total size is {twod_array.nbytes} bytes.")

**********************************************************************
Array has type int16 which means that every item takes 2 bytes.
2D Array has 3 elements.
Array total size is 6 bytes.
**********************************************************************
2D Array has type int32 which means that every item takes 4 bytes.
2D Array has 6 elements.
2D Array total size is 24 bytes.


## Reading Elements 

In [9]:
x = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(x)
print(f"Shape:{x.shape}")

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape:(2, 7)


### Read an element with index

In [10]:
print("The fourth element in the second row is:")
print(x[1, 3]) # Indexes are starting from 0

The fourth element in the second row is:
11


In [11]:
print("The sixth element in the first row is:")
print(x[0, 5]) # Indexes are starting from 0

The sixth element in the first row is:
6


In [12]:
print("The sixth element in the first row is:")
print(x[0, -2]) # Negative indexes go from the back of the array

The sixth element in the first row is:
6


### Read a complete row

In [13]:
print("The first row is:")
print(x[0, :])

The first row is:
[1 2 3 4 5 6 7]


In [14]:
print("The second row is:")
print(x[1, :])

The second row is:
[ 8  9 10 11 12 13 14]


In [15]:
print("The second row is:")
print(x[-1, :]) # Negative indexes go from the back

The second row is:
[ 8  9 10 11 12 13 14]


### Read a complete column

In [16]:
print("The first column is:")
print(x[:, 0])

The first column is:
[1 8]


In [17]:
print("The second column is:")
print(x[:, 1])

The second column is:
[2 9]


In [18]:
print("The last column is:")
print(x[:, -1]) # Negative indexes go from the back

The last column is:
[ 7 14]


### Read a subset 

In [19]:
print("The first 3 elements from the first row:")
print(x[0, 0:3])

The first 3 elements from the first row:
[1 2 3]


In [20]:
print("The 3 elements from the second row, starting from the third element:")
print(x[1, 2:5])

The 3 elements from the second row, starting from the third element:
[10 11 12]


### Update a Value

In [21]:
# Replace the value of the 6th element in the second row with 33
x[1, 5] = 33
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 33 14]]


In [22]:
# Bulk Update 
# Replace elements from third to fifth in the first row with value 56

x[0, 2:5] = 56
print(x)

[[ 1  2 56 56 56  6  7]
 [ 8  9 10 11 12 33 14]]


### Boolean Indexing

In [23]:
x > 10

array([[False, False,  True,  True,  True, False, False],
       [False, False, False,  True,  True,  True,  True]])

## Initialize Different Types of Arrays

In [24]:
# All zeros 5x6 matrix 
zeros = np.zeros((5, 6))
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
# All ones 5x6 matrix 
ones = np.ones((5, 6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [26]:
# Any other number 5x6 matrix 
ninenine = np.full((5,6), 99)
print(ninenine)

[[99 99 99 99 99 99]
 [99 99 99 99 99 99]
 [99 99 99 99 99 99]
 [99 99 99 99 99 99]
 [99 99 99 99 99 99]]


In [27]:
# Any other number with dimensions from another array (full_like)
fivefive = np.full_like(x, 55)
print(fivefive)

[[55 55 55 55 55 55 55]
 [55 55 55 55 55 55 55]]


In [28]:
# 5x6 matrix with random float numbers
randomize = np.random.rand(5, 6)
print(randomize)

[[0.96285976 0.00931921 0.61453111 0.6846065  0.17965427 0.92548501]
 [0.78119724 0.25421679 0.33713402 0.78393532 0.44122679 0.24001506]
 [0.27472269 0.99649043 0.48591665 0.13464157 0.39398014 0.16291523]
 [0.48315635 0.33255073 0.16103341 0.55914281 0.59750496 0.80263915]
 [0.08985945 0.84173854 0.87351364 0.3576588  0.3742723  0.00807349]]


In [29]:
# 5x6 matrix with random int numbers
randomizeint = np.random.randint(6, size=(5,6))
print(randomizeint)

[[5 0 1 3 5 4]
 [3 5 3 4 1 5]
 [1 3 1 0 3 4]
 [1 3 2 3 0 4]
 [2 1 2 4 3 2]]


In [30]:
# 3x3 identity matrix
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# Repeat
print(f"*************************Initial*********************************")
initial = np.array([[2, 11, 9]])
print(initial)

print(f"*************************Expended1*******************************")
expanded1 = np.repeat(initial, 3, axis=1)
print(expanded1)

print(f"*************************Expended2*******************************")
expanded2 = np.repeat(initial, 3, axis=0)
print(expanded2)

*************************Initial*********************************
[[ 2 11  9]]
*************************Expended1*******************************
[[ 2  2  2 11 11 11  9  9  9]]
*************************Expended2*******************************
[[ 2 11  9]
 [ 2 11  9]
 [ 2 11  9]]


In [32]:
# Stack

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

stacked = np.vstack([array1, array2])
print(stacked)

[[1 2 3]
 [4 5 6]]


In [33]:
# Reshape

stacked.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## Operations with scalars

In [37]:
y = np.array([1, 2, 3, 4, 5, 6])
print(y)

[1 2 3 4 5 6]


In [38]:
print(y + 3)

[4 5 6 7 8 9]


In [39]:
print(y - 3)

[-2 -1  0  1  2  3]


In [40]:
print(y * 3)

[ 3  6  9 12 15 18]


In [41]:
print(y ** 3)

[  1   8  27  64 125 216]


In [42]:
print(y / 3)

[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.        ]


## Operations with other arrays

In [43]:
z = np.array([6, 5, 4, 3, 2, 1])

In [44]:
print(y + z)

[7 7 7 7 7 7]


In [45]:
print(y - z)

[-5 -3 -1  1  3  5]


In [46]:
print(y * z)

[ 6 10 12 12 10  6]


In [47]:
print(y / z)

[0.16666667 0.4        0.75       1.33333333 2.5        6.        ]


## Linear Algebra

In [48]:
x = np.ones((2, 3))
y = np.full((3, 2), 6)

print(x)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6]
 [6 6]
 [6 6]]


In [49]:
# Matrix multiplication
np.matmul(x, y)

array([[18., 18.],
       [18., 18.]])

In [50]:
# Derminant of 3x3 identity matrix
np.linalg.det(np.identity(3))

1.0

## Statsics with NumPy

In [34]:
x = np.random.randint(10, size=11)
print(x)

[9 5 5 3 0 2 8 5 2 2 2]


In [35]:
np.max(x)

9

In [36]:
np.min(x)

0

In [53]:
np.mean(x)

1.0

In [54]:
np.median(x)

1.0

## Trigonometry

In [51]:
np.sin(y)

array([[-0.2794155, -0.2794155],
       [-0.2794155, -0.2794155],
       [-0.2794155, -0.2794155]])

In [52]:
np.cos(y)

array([[0.96017029, 0.96017029],
       [0.96017029, 0.96017029],
       [0.96017029, 0.96017029]])