In [5]:
import torch
import numpy as np

## Tensors

In [3]:
# Scalar
tensor_1 = torch.tensor(11.)
print('------ Scalar ------')
print(tensor_1)
print(tensor_1.dtype)
print(tensor_1.shape)
print('\n')

# Vector
tensor_2 = torch.tensor([11, 23, 9, 33])
print('------ Vector ------')
print(tensor_2)
print(tensor_2.dtype)
print(tensor_2.shape)
print('\n')

# Matrix
tensor_3 = torch.tensor([[5., 6], 
                   [7, 4], 
                   [9, 11]])

print('------ Matrix ------')
print(tensor_3)
print(tensor_3.dtype)
print(tensor_3.shape)
print('\n')

# 3D Array
tensor_4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

print('------ 3D Array ------')
print(tensor_4)
print(tensor_4.dtype)
print(tensor_4.shape)
print('\n')

------ Scalar ------
tensor(11.)
torch.float32
torch.Size([])


------ Vector ------
tensor([11, 23,  9, 33])
torch.int64
torch.Size([4])


------ Matrix ------
tensor([[ 5.,  6.],
        [ 7.,  4.],
        [ 9., 11.]])
torch.float32
torch.Size([3, 2])


------ 3D Array ------
tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.float32
torch.Size([2, 2, 3])




In [4]:
# Uninitialized (does not contain definite known values before it is used.)
tensor = torch.empty(2, 3)
print(tensor)

# Tensor with all zeroes
tensor = torch.zeros(2, 3)
print(tensor)

# Tensor with all ones
tensor = torch.ones(2, 3)
print(tensor)

# Tensor with randomly initialized values
tensor = torch.rand(2, 3)
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4878, 0.0805, 0.9782],
        [0.4288, 0.4309, 0.4090]])


In [6]:
numpy_array = np.array([[1, 2], [3, 4.]])
print(numpy_array)
print('\n')

tensor = torch.from_numpy(numpy_array)
print(tensor)
print('\n')

re_numpy_array = tensor.numpy()
print(re_numpy_array)

[[1. 2.]
 [3. 4.]]


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


[[1. 2.]
 [3. 4.]]


## Tensor Operations

In [7]:
x = torch.tensor(3.)
w = torch.tensor(4.)
b = torch.tensor(5.)

res = w*x + b
res

tensor(17.)

In [8]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)

result1 = x + y
result2 = torch.add(x, y)

print(result1)
print(result2)

tensor([[0.4331, 1.0239, 1.8545],
        [0.0738, 1.0001, 1.5300]])
tensor([[0.4331, 1.0239, 1.8545],
        [0.0738, 1.0001, 1.5300]])


In [9]:
tensor = torch.randn(3, 3)
reshaped = tensor.view(9)

print(tensor, tensor.size())
print(reshaped, reshaped.size())

tensor([[-0.5283, -1.0336, -0.9913],
        [-0.7726, -0.3270,  0.5878],
        [ 0.3022,  0.1859, -2.1970]]) torch.Size([3, 3])
tensor([-0.5283, -1.0336, -0.9913, -0.7726, -0.3270,  0.5878,  0.3022,  0.1859,
        -2.1970]) torch.Size([9])


In [10]:
tensor = torch.randn(3, 3)
print(tensor[:, 1])

tensor([-0.6772, -0.7194,  0.4562])


## Gradients

In [19]:
tensor = torch.randn(3, 3)
tensor = torch.autograd.Variable(tensor, requires_grad=True)
print(tensor[:, 1])

tensor([-0.3928, -0.6941,  1.4670], grad_fn=<SelectBackward>)


In [20]:
increased = tensor + 2
print(increased)

tensor([[2.7186, 1.6072, 3.4084],
        [2.6568, 1.3059, 0.5820],
        [2.4901, 3.4670, 2.4983]], grad_fn=<AddBackward0>)


In [21]:
temp = increased * increased * 3
output = temp.mean()
output.backward()

print(tensor.grad)

tensor([[1.8124, 1.0715, 2.2723],
        [1.7712, 0.8706, 0.3880],
        [1.6600, 2.3113, 1.6655]])
